name = "forest-explorer"
main = "build/worker/shim.mjs"
compatibility_date = "2024-07-13"
# ChainSafe Static Hosting
account_id = '2238a825c5aca59233eab1f221f7aefb'

routes = [
	{ pattern = "forest-explorer.chainsafe.dev", custom_domain = true }
]

[build]
command = "mkdir -p pkg && cp public/* pkg/ && npx tailwindcss --minify -i style/tailwind.css -o pkg/style.css && wasm-pack build --no-typescript --release --target web --out-name client --features hydrate --no-default-features && worker-build --release --features ssr --no-default-features"
