name = "forest-explorer"
main = "build/worker/shim.mjs"
compatibility_date = "2024-07-13"
# ChainSafe Static Hosting
account_id = '2238a825c5aca59233eab1f221f7aefb'

routes = [{ pattern = "forest-explorer.chainsafe.dev", custom_domain = true }]

[durable_objects]
bindings = [{ name = "RATE_LIMITER", class_name = "RateLimiter" }]

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]

[assets]
directory = "assets"

[observability.logs]
enabled = true

[build]
command = """
yarn assets &&
yarn css-minify &&
yarn wasm-pack &&
worker-build --release --features ssr --no-default-features
"""

[env.quick]
kv_namespaces = [{ binding = "RATE_LIMIT", id = "4dc6f9a495dc44849d2c3c9066f23dca" }]
[env.quick.build]
command = """
yarn assets &&
yarn css-minify &&
yarn wasm-pack-dev &&
worker-build --dev --no-opt --features ssr --no-default-features
"""

[env.prebuilt]
kv_namespaces = [{ binding = "RATE_LIMIT", id = "4dc6f9a495dc44849d2c3c9066f23dca" }]
[env.prebuilt.build]
command = ""
